In [1]:
import numpy as np
import gym

In [2]:
env = gym.make("FrozenLake-v1")
n_observations = env.observation_space.n
n_actions = env.action_space.n

/usr/local/lib/python3.8/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.8/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [3]:
#Initialize the Q-table to 0
Q_table = np.zeros((n_observations,n_actions))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
#number of episode we will run
n_episodes = 10000

#maximum of iteration per episode
max_iter_episode = 100

#initialize the exploration probability to 1
exploration_proba = 1

#exploartion decreasing decay for exponential decreasing
exploration_decreasing_decay = 0.001

# minimum of exploration proba
min_exploration_proba = 0.01

#discounted factor
gamma = 0.99

#learning rate
lr = 0.1

In [29]:
total_rewards_episode = list()

In [30]:
#we iterate over episodes
for e in range(n_episodes):
    #we initialize the first state of the episode
    current_state = env.reset()
    done = False
    
    #sum the rewards that the agent gets from the environment
    total_episode_reward = 0
    
    for i in range(max_iter_episode): 
        # we sample a float from a uniform distribution over 0 and 1
        # if the sampled flaot is less than the exploration proba
        #     the agent selects arandom action
        # else
        #     he exploits his knowledge using the bellman equation 
        
        if np.random.uniform(0,1) < exploration_proba:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q_table[current_state,:])
        
        # The environment runs the chosen action and returns
        # the next state, a reward and true if the epiosed is ended.
        next_state, reward, done, _ = env.step(action)
        
        # We update our Q-table using the Q-learning iteration
        Q_table[current_state, action] = (1-lr) * Q_table[current_state, action] +lr*(reward + gamma*max(Q_table[next_state,:]))
        total_episode_reward += reward
        # If the episode is finished, we leave the for loop
        if done:
            break
        current_state = next_state
    #We update the exploration proba using exponential decay formula 
    exploration_proba = max(min_exploration_proba, np.exp(-exploration_decreasing_decay*e))
    total_rewards_episode.append(total_episode_reward)

In [31]:
print("Mean reward per thousand episodes")
for i in range(10):
    print(f"{(i+1)*1000}: mean espiode reward: {np.mean(total_rewards_episode[1000*i:1000*(i+1)])}")

Mean reward per thousand episodes
1000: mean espiode reward: 0.054
2000: mean espiode reward: 0.232
3000: mean espiode reward: 0.446
4000: mean espiode reward: 0.581
5000: mean espiode reward: 0.67
6000: mean espiode reward: 0.702
7000: mean espiode reward: 0.703
8000: mean espiode reward: 0.683
9000: mean espiode reward: 0.675
10000: mean espiode reward: 0.685


In [32]:
Q_table

array([[0.57682487, 0.54200049, 0.51518813, 0.51374319],
       [0.24928177, 0.34827999, 0.34262678, 0.53005142],
       [0.43647244, 0.42760149, 0.42414091, 0.48627636],
       [0.28127904, 0.32058023, 0.34538009, 0.47020522],
       [0.60161581, 0.35210911, 0.23750153, 0.36754199],
       [0.        , 0.        , 0.        , 0.        ],
       [0.32509104, 0.21105555, 0.21668728, 0.10291924],
       [0.        , 0.        , 0.        , 0.        ],
       [0.45568092, 0.37969775, 0.39296602, 0.6662461 ],
       [0.42630769, 0.71545623, 0.41826643, 0.46110979],
       [0.69127231, 0.34514193, 0.3788338 , 0.33627272],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.30032979, 0.63590317, 0.78218105, 0.45432522],
       [0.71472409, 0.89826561, 0.78559449, 0.74995767],
       [0.        , 0.        , 0.        , 0.        ]])